<?php
declare(strict_types=1);
require dirname(__DIR__) . '/src/bootstrap.php'; require dirname(__DIR__) . '/src/admin_layout.php'; Auth::requireAdmin();
$page=max(1,(int)($_GET['page']??1)); $per=50; $where=[]; $params=[];
foreach(['level','channel','correlation_id','event_id','participant_id','notification_message_id','subscription_id','http_code'] as $f){ if(($_GET[$f]??'')!==''){ $where[]="$f=?"; $params[]=$_GET[$f]; }}
if(($_GET['q']??'')!==''){ $where[]='(message LIKE ? OR context_json LIKE ?)'; $params[]='%'.$_GET['q'].'%'; $params[]='%'.$_GET['q'].'%'; }
$tz=app_config()['timezone'] ?? 'America/Sao_Paulo';
if(($_GET['from']??'')!==''){ $where[]='created_at>=?'; $params[]=utc_from_local($_GET['from'].' 00:00:00',$tz); } if(($_GET['to']??'')!==''){ $where[]='created_at<=?'; $params[]=utc_from_local($_GET['to'].' 23:59:59',$tz); }
$sql='FROM system_logs'.($where?' WHERE '.implode(' AND ',$where):''); $count=db()->prepare('SELECT COUNT(*) '.$sql); $count->execute($params); $total=(int)$count->fetchColumn();
$stmt=db()->prepare('SELECT * '.$sql.' ORDER BY created_at DESC LIMIT '.$per.' OFFSET '.(($page-1)*$per)); $stmt->execute($params); $rows=$stmt->fetchAll();
$detail=null; $history=[]; if(isset($_GET['id'])){ $d=db()->prepare('SELECT * FROM system_logs WHERE id=?'); $d->execute([(int)$_GET['id']]); $detail=$d->fetch(); if($detail&&$detail['correlation_id']){ $h=db()->prepare('SELECT * FROM system_logs WHERE correlation_id=? ORDER BY created_at ASC LIMIT 100'); $h->execute([$detail['correlation_id']]); $history=$h->fetchAll(); }}
admin_header('Logs e diagnóstico','diagnostics'); ?>
<div class="toolbar"><a class="btn btn-secondary" href="<?= e(app_url('admin/diagnostics.php')) ?>">Diagnóstico</a></div>
<section class="card panel"><form class="form-grid" method="get"><label>De<input type="date" name="from" value="<?=e($_GET['from']??'')?>"></label><label>Até<input type="date" name="to" value="<?=e($_GET['to']??'')?>"></label><label>Nível<input name="level" value="<?=e($_GET['level']??'')?>"></label><label>Canal<input name="channel" value="<?=e($_GET['channel']??'')?>"></label><label>Correlation ID<input name="correlation_id" value="<?=e($_GET['correlation_id']??'')?>"></label><label>HTTP<input name="http_code" value="<?=e($_GET['http_code']??'')?>"></label><label>Evento<input name="event_id" value="<?=e($_GET['event_id']??'')?>"></label><label>Participante<input name="participant_id" value="<?=e($_GET['participant_id']??'')?>"></label><label>Mensagem<input name="notification_message_id" value="<?=e($_GET['notification_message_id']??'')?>"></label><label>Assinatura<input name="subscription_id" value="<?=e($_GET['subscription_id']??'')?>"></label><label class="span-2">Texto<input name="q" value="<?=e($_GET['q']??'')?>"></label><button class="btn btn-primary">Filtrar</button></form></section>
<section class="card panel"><p><?= $total ?> registros · horários exibidos em <?= e($tz) ?></p><div class="table-wrap"><table class="data-table"><tr><th>Data</th><th>Nível</th><th>Canal</th><th>Mensagem</th><th>Corr.</th><th>HTTP</th><th></th></tr><?php foreach($rows as $r): ?><tr><td><?=e(local_from_utc($r['created_at'],$tz,'d/m/Y H:i:s'))?></td><td><?=e($r['level'])?></td><td><?=e($r['channel'])?></td><td><?=e($r['message'])?></td><td><?=e($r['correlation_id'])?></td><td><?=e((string)$r['http_code'])?></td><td><a href="?id=<?=$r['id']?>">abrir</a></td></tr><?php endforeach; ?></table></div><?php if($page>1):?><a href="?page=<?=$page-1?>">Anterior</a><?php endif;?> <?php if($total>$page*$per):?><a href="?page=<?=$page+1?>">Próxima</a><?php endif;?></section>
<?php if($detail): ?><section class="card panel"><h2>Registro #<?= (int)$detail['id']?></h2><pre><?= e(json_encode($detail, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?></pre><h3>Histórico do correlation ID</h3><?php foreach($history as $h): ?><p><strong><?=e(local_from_utc($h['created_at'],$tz,'d/m/Y H:i:s'))?> <?=e($h['channel'])?></strong> <?=e($h['message'])?></p><?php endforeach; ?><p class="muted">Recomendação: para falhas Push, confira HTTP, provider_response, VAPID, HTTPS e assinatura expirada.</p></section><?php endif; ?>
<?php admin_footer(); ?>
